<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SOTA0LM" failures="1" tests="6" name="com.testcases.AccountCreation_Test" time="181.648" errors="0" timestamp="2022-10-06T13:47:09 EDT" skipped="0">
  <testcase classname="com.testcases.AccountCreation_Test" name="test_AccountCreation" time="30.285"/>
  <system-out/>
  <testcase classname="com.testcases.AccountCreation_Test" name="test_AccountCreation" time="28.914"/>
  <system-out/>
  <testcase classname="com.testcases.AccountCreation_Test" name="test_AccountCreation" time="21.686"/>
  <system-out/>
  <testcase classname="com.testcases.AccountCreation_Test" name="test_AccountCreation" time="39.505"/>
  <system-out/>
  <testcase classname="com.testcases.AccountCreation_Test" name="test_AccountCreation" time="25.905"/>
  <system-out/>
  <testcase classname="com.testcases.AccountCreation_Test" name="test_AccountCreation" time="35.353">
    <failure message="expected [http://automationpractice.com/index.php?controller=authentication] but found [http://automationpractice.com/index.php?controller=my-account]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [http://automationpractice.com/index.php?controller=authentication] but found [http://automationpractice.com/index.php?controller=my-account]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.testcases.AccountCreation_Test.test_AccountCreation(AccountCreation_Test.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- test_AccountCreation -->
  <system-out/>
</testsuite> <!-- com.testcases.AccountCreation_Test -->
